[package]
authors = ["cloudcalvin <cloudcalvin@me.com>"]
name = "vpr2bitstream-rs"
version = "0.1.0"

[dependencies]
derive_builder = "0.3.0"
error-chain = "*"
lazy_static = "0.2.4"
regex = "*"

[dependencies.nalgebra]
version = "0.11"

[dependencies.nom]
features = ["regexp"]
version = "^2.1"
